xychart-beta
    title "Sales Revenue 2024"
    x-axis [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
    y-axis "Revenue (in thousands)" 0 --> 100
    bar [45, 52, 48, 61, 58, 65, 72, 78, 75, 82, 88, 95]
    line [40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]
